spring:
  application:
    name: spring-cloud-gateway-server
  redis:
    port: 6379
    host: localhost
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://user-service
          predicates:
            - Path=/gateway/**
            - Auth=authkey,authValue # 自定义predicate断言 AuthRoutePredicateFactory
          filters:
            - StripPrefix=1  # 1 表示跳过/gateway
            - Custom=kangping  # 自定义过滤器 CustomGatewayFilterFactory
        - id: requestratelimiter_route
          predicates:
            - Path=/limit/**
          uri: lb://user-service
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@urlKeyResolver}"
                redis-rate-limiter.replenishRate: 10 # 每天生成的token 数
                redis-rate-limiter.burstCapacity: 20 # 桶的总容量
                redis-rate-limiter.requestedTokens: 1
      discovery:
        locator:
          enabled: true #打开解析器 解析lb://
          lower-case-service-id: true # 以小写匹配


server:
  port: 9093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka


management:
  endpoint:
    gateway:
      enabled: true #打开gateway的端点支持
  endpoints:
    web:
      exposure:
        include: gateway # 打开gateway路由信息端点

